// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Hobby: typeof import('./src/components/view/about/Hobby.vue')['default']
    IIcSharpDevices: typeof import('~icons/ic/sharp-devices')['default']
    IIcSharpMovie: typeof import('~icons/ic/sharp-movie')['default']
    IMdiBasketball: typeof import('~icons/mdi/basketball')['default']
    IMdiBike: typeof import('~icons/mdi/bike')['default']
    IMdiPotSteamOutline: typeof import('~icons/mdi/pot-steam-outline')['default']
    IRiSteamLine: typeof import('~icons/ri/steam-line')['default']
    ISimpleIconsHtml5: typeof import('~icons/simple-icons/html5')['default']
    IUilAt: typeof import('~icons/uil/at')['default']
    IUilCodeBranch: typeof import('~icons/uil/code-branch')['default']
    IUilGithubAlt: typeof import('~icons/uil/github-alt')['default']
    IUilLinkedinAlt: typeof import('~icons/uil/linkedin-alt')['default']
    IUilUsersAlt: typeof import('~icons/uil/users-alt')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skill: typeof import('./src/components/view/about/Skill.vue')['default']
    Skills: typeof import('./src/components/view/about/Skills.vue')['default']
    Timeline: typeof import('./src/components/view/about/Timeline.vue')['default']
    Whatcando: typeof import('./src/components/view/about/Whatcando.vue')['default']
  }
}
